version: 2

registries:
  ghcr:
    type: docker-registry
    url: https://ghcr.io

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - aszili

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    assignees:
      - aszili
    registries:
      - ghcr